name = "czmq_ada_examples"
version = "0.3.0"
description = "Example programs demonstrating the CZMQ Ada bindings"
tags = ["zeromq", "examples"]
licenses = "MPL-2.0"
authors = ["Jochen Lillich <contact@geewiz.dev>"]
maintainers = ["Jochen Lillich <contact@geewiz.dev>"]
maintainers-logins = ["geewiz"]

project-files = ["examples.gpr"]

executables = ["push_pull", "publisher", "subscriber"]

[[depends-on]]
czmq_ada = "~0.3"
