name: Ada

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install CZMQ development library
      run: sudo apt-get update && sudo apt-get install -y libczmq-dev

    - name: Set up Alire
      uses: alire-project/setup-alire@v4

    - name: Build library
      run: alr build

    - name: Build tests
      run: alr build
      working-directory: tests

    - name: Run tests
      working-directory: tests
      run: |
        bin/test_sockets
        bin/test_sockets_curve
        bin/test_certificates
        bin/test_authentication

    - name: Build examples
      run: alr build
      working-directory: examples
